specVersion: 0.0.1
description: ''
repository: https://github.com/Phala-Network/khala-subbridge-subquery.git
schema: ./schema.graphql
network:
  endpoint: wss://khala.api.onfinality.io/public-ws
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1617952
    mapping:
      handlers:
        - handler: handleXTransferWithdrawn
          kind: substrate/EventHandler
          filter:
            module: xTransfer
            method: Withdrawn
        - handler: handleXTransferDeposited
          kind: substrate/EventHandler
          filter:
            module: xTransfer
            method: Deposited
        - handler: handleXTransferForwarded
          kind: substrate/EventHandler
          filter:
            module: xTransfer
            method: Forwarded
        - handler: handleXcmbridgeTransferedEvent
          kind: substrate/EventHandler
          filter:
            module: xcmBridge
            method: AssetTransfered
        - handler: handleChainbridgeFungibleTransfer
          kind: substrate/EventHandler
          filter:
            module: chainBridge
            method: FungibleTransfer
        - handler: handleChainbridgeProposalVoteFor
          kind: substrate/EventHandler
          filter:
            module: chainBridge
            method: VoteFor
        - handler: handleChainbridgeProposalApproved
          kind: substrate/EventHandler
          filter:
            module: chainBridge
            method: ProposalApproved
        - handler: handleChainbridgeProposalSucceeded
          kind: substrate/EventHandler
          filter:
            module: chainBridge
            method: ProposalSucceeded
        - handler: handleChainbridgeProposalRejected
          kind: substrate/EventHandler
          filter:
            module: chainBridge
            method: ProposalRejected
        - handler: handleChainbridgeProposalFailed
          kind: substrate/EventHandler
          filter:
            module: chainBridge
            method: ProposalFailed
