specVersion: 0.2.0
name: subbridge-subquery
version: 0.0.1
description: 'SubBridge index service build on top of SubQuery'
repository: https://github.com/Phala-Network/khala-subbridge-subquery.git
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xd43540ba6d3eb4897c28a77d48cb5b729fea37603cbbfc7a86a73b72adb3be8d'
  endpoint: wss://khala.api.onfinality.io/public-ws,
  dictionary: 'https://api.subquery.network/sq/subquery/khala-dictionary'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1617952
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleXTransferWithdrawn
          kind: substrate/EventHandler
          filter:
            module: xTransfer
            method: Withdrawn
        - handler: handleXTransferDeposited
          kind: substrate/EventHandler
          filter:
            module: xTransfer
            method: Deposited
        - handler: handleXTransferForwarded
          kind: substrate/EventHandler
          filter:
            module: xTransfer
            method: Forwarded
        - handler: handleXcmbridgeTransferedEvent
          kind: substrate/EventHandler
          filter:
            module: xcmBridge
            method: AssetTransfered
        - handler: handleChainbridgeFungibleTransfer
          kind: substrate/EventHandler
          filter:
            module: chainBridge
            method: FungibleTransfer
        - handler: handleChainbridgeProposalVoteFor
          kind: substrate/EventHandler
          filter:
            module: chainBridge
            method: VoteFor
        - handler: handleChainbridgeProposalApproved
          kind: substrate/EventHandler
          filter:
            module: chainBridge
            method: ProposalApproved
        - handler: handleChainbridgeProposalSucceeded
          kind: substrate/EventHandler
          filter:
            module: chainBridge
            method: ProposalSucceeded
        - handler: handleChainbridgeProposalRejected
          kind: substrate/EventHandler
          filter:
            module: chainBridge
            method: ProposalRejected
        - handler: handleChainbridgeProposalFailed
          kind: substrate/EventHandler
          filter:
            module: chainBridge
            method: ProposalFailed
